/*
Dropbox Sign API

Dropbox Sign v3 API

API version: 3.0.0
Contact: apisupport@hellosign.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SubFormFieldsPerDocumentSignature type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubFormFieldsPerDocumentSignature{}

// SubFormFieldsPerDocumentSignature This class extends `SubFormFieldsPerDocumentBase`.
type SubFormFieldsPerDocumentSignature struct {
	SubFormFieldsPerDocumentBase
	// A signature input field. Use the `SubFormFieldsPerDocumentSignature` class.
	Type string `json:"type"`
}

// NewSubFormFieldsPerDocumentSignature instantiates a new SubFormFieldsPerDocumentSignature object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubFormFieldsPerDocumentSignature(type_ string, documentIndex int32, apiId string, height int32, required bool, signer string, width int32, x int32, y int32) *SubFormFieldsPerDocumentSignature {
	this := SubFormFieldsPerDocumentSignature{}
	this.DocumentIndex = documentIndex
	this.ApiId = apiId
	this.Height = height
	this.Required = required
	this.Signer = signer
	this.Type = type_
	this.Width = width
	this.X = x
	this.Y = y
	return &this
}

// NewSubFormFieldsPerDocumentSignatureWithDefaults instantiates a new SubFormFieldsPerDocumentSignature object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubFormFieldsPerDocumentSignatureWithDefaults() *SubFormFieldsPerDocumentSignature {
	this := SubFormFieldsPerDocumentSignature{}
	var type_ string = "signature"
	this.Type = type_
	return &this
}

// GetType returns the Type field value
func (o *SubFormFieldsPerDocumentSignature) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SubFormFieldsPerDocumentSignature) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SubFormFieldsPerDocumentSignature) SetType(v string) {
	o.Type = v
}

func (o SubFormFieldsPerDocumentSignature) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubFormFieldsPerDocumentSignature) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedSubFormFieldsPerDocumentBase, errSubFormFieldsPerDocumentBase := json.Marshal(o.SubFormFieldsPerDocumentBase)
	if errSubFormFieldsPerDocumentBase != nil {
		return map[string]interface{}{}, errSubFormFieldsPerDocumentBase
	}
	errSubFormFieldsPerDocumentBase = json.Unmarshal([]byte(serializedSubFormFieldsPerDocumentBase), &toSerialize)
	if errSubFormFieldsPerDocumentBase != nil {
		return map[string]interface{}{}, errSubFormFieldsPerDocumentBase
	}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

type NullableSubFormFieldsPerDocumentSignature struct {
	value *SubFormFieldsPerDocumentSignature
	isSet bool
}

func (v NullableSubFormFieldsPerDocumentSignature) Get() *SubFormFieldsPerDocumentSignature {
	return v.value
}

func (v *NullableSubFormFieldsPerDocumentSignature) Set(val *SubFormFieldsPerDocumentSignature) {
	v.value = val
	v.isSet = true
}

func (v NullableSubFormFieldsPerDocumentSignature) IsSet() bool {
	return v.isSet
}

func (v *NullableSubFormFieldsPerDocumentSignature) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubFormFieldsPerDocumentSignature(val *SubFormFieldsPerDocumentSignature) *NullableSubFormFieldsPerDocumentSignature {
	return &NullableSubFormFieldsPerDocumentSignature{value: val, isSet: true}
}

func (v NullableSubFormFieldsPerDocumentSignature) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubFormFieldsPerDocumentSignature) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


