/*
Dropbox Sign API

Dropbox Sign v3 API

API version: 3.0.0
Contact: apisupport@hellosign.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TemplateCreateEmbeddedResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateCreateEmbeddedResponse{}

// TemplateCreateEmbeddedResponse struct for TemplateCreateEmbeddedResponse
type TemplateCreateEmbeddedResponse struct {
	Template *TemplateCreateEmbeddedResponse `json:"template,omitempty"`
	// A list of warnings.
	Warnings []WarningResponse `json:"warnings,omitempty"`
}

// NewTemplateCreateEmbeddedResponse instantiates a new TemplateCreateEmbeddedResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateCreateEmbeddedResponse() *TemplateCreateEmbeddedResponse {
	this := TemplateCreateEmbeddedResponse{}
	return &this
}

// NewTemplateCreateEmbeddedResponseWithDefaults instantiates a new TemplateCreateEmbeddedResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateCreateEmbeddedResponseWithDefaults() *TemplateCreateEmbeddedResponse {
	this := TemplateCreateEmbeddedResponse{}
	return &this
}

// GetTemplate returns the Template field value if set, zero value otherwise.
func (o *TemplateCreateEmbeddedResponse) GetTemplate() TemplateCreateEmbeddedResponse {
	if o == nil || IsNil(o.Template) {
		var ret TemplateCreateEmbeddedResponse
		return ret
	}
	return *o.Template
}

// GetTemplateOk returns a tuple with the Template field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateCreateEmbeddedResponse) GetTemplateOk() (*TemplateCreateEmbeddedResponse, bool) {
	if o == nil || IsNil(o.Template) {
		return nil, false
	}
	return o.Template, true
}

// HasTemplate returns a boolean if a field has been set.
func (o *TemplateCreateEmbeddedResponse) HasTemplate() bool {
	if o != nil && !IsNil(o.Template) {
		return true
	}

	return false
}

// SetTemplate gets a reference to the given TemplateCreateEmbeddedResponse and assigns it to the Template field.
func (o *TemplateCreateEmbeddedResponse) SetTemplate(v TemplateCreateEmbeddedResponse) {
	o.Template = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *TemplateCreateEmbeddedResponse) GetWarnings() []WarningResponse {
	if o == nil || IsNil(o.Warnings) {
		var ret []WarningResponse
		return ret
	}
	return o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateCreateEmbeddedResponse) GetWarningsOk() ([]WarningResponse, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *TemplateCreateEmbeddedResponse) HasWarnings() bool {
	if o != nil && !IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []WarningResponse and assigns it to the Warnings field.
func (o *TemplateCreateEmbeddedResponse) SetWarnings(v []WarningResponse) {
	o.Warnings = v
}

func (o TemplateCreateEmbeddedResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateCreateEmbeddedResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Template) {
		toSerialize["template"] = o.Template
	}
	if !IsNil(o.Warnings) {
		toSerialize["warnings"] = o.Warnings
	}
	return toSerialize, nil
}

type NullableTemplateCreateEmbeddedResponse struct {
	value *TemplateCreateEmbeddedResponse
	isSet bool
}

func (v NullableTemplateCreateEmbeddedResponse) Get() *TemplateCreateEmbeddedResponse {
	return v.value
}

func (v *NullableTemplateCreateEmbeddedResponse) Set(val *TemplateCreateEmbeddedResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateCreateEmbeddedResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateCreateEmbeddedResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateCreateEmbeddedResponse(val *TemplateCreateEmbeddedResponse) *NullableTemplateCreateEmbeddedResponse {
	return &NullableTemplateCreateEmbeddedResponse{value: val, isSet: true}
}

func (v NullableTemplateCreateEmbeddedResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateCreateEmbeddedResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


