/*
Dropbox Sign API

Dropbox Sign v3 API

API version: 3.0.0
Contact: apisupport@hellosign.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TemplateResponseDocumentStaticFieldSignature type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateResponseDocumentStaticFieldSignature{}

// TemplateResponseDocumentStaticFieldSignature This class extends `TemplateResponseDocumentStaticFieldBase`
type TemplateResponseDocumentStaticFieldSignature struct {
	// The type of this static field. See [field types](/api/reference/constants/#field-types).  * Text Field uses `TemplateResponseDocumentStaticFieldText` * Dropdown Field uses `TemplateResponseDocumentStaticFieldDropdown` * Hyperlink Field uses `TemplateResponseDocumentStaticFieldHyperlink` * Checkbox Field uses `TemplateResponseDocumentStaticFieldCheckbox` * Radio Field uses `TemplateResponseDocumentStaticFieldRadio` * Signature Field uses `TemplateResponseDocumentStaticFieldSignature` * Date Signed Field uses `TemplateResponseDocumentStaticFieldDateSigned` * Initials Field uses `TemplateResponseDocumentStaticFieldInitials`
	Type string `json:"type"`
}

// NewTemplateResponseDocumentStaticFieldSignature instantiates a new TemplateResponseDocumentStaticFieldSignature object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateResponseDocumentStaticFieldSignature(type_ string) *TemplateResponseDocumentStaticFieldSignature {
	this := TemplateResponseDocumentStaticFieldSignature{}
	this.Type = type_
	var signer string = "me_now"
	this.Signer = &signer
	return &this
}

// NewTemplateResponseDocumentStaticFieldSignatureWithDefaults instantiates a new TemplateResponseDocumentStaticFieldSignature object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateResponseDocumentStaticFieldSignatureWithDefaults() *TemplateResponseDocumentStaticFieldSignature {
	this := TemplateResponseDocumentStaticFieldSignature{}
	var type_ string = "signature"
	this.Type = type_
	return &this
}

// GetType returns the Type field value
func (o *TemplateResponseDocumentStaticFieldSignature) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TemplateResponseDocumentStaticFieldSignature) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TemplateResponseDocumentStaticFieldSignature) SetType(v string) {
	o.Type = v
}

func (o TemplateResponseDocumentStaticFieldSignature) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateResponseDocumentStaticFieldSignature) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

type NullableTemplateResponseDocumentStaticFieldSignature struct {
	value *TemplateResponseDocumentStaticFieldSignature
	isSet bool
}

func (v NullableTemplateResponseDocumentStaticFieldSignature) Get() *TemplateResponseDocumentStaticFieldSignature {
	return v.value
}

func (v *NullableTemplateResponseDocumentStaticFieldSignature) Set(val *TemplateResponseDocumentStaticFieldSignature) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateResponseDocumentStaticFieldSignature) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateResponseDocumentStaticFieldSignature) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateResponseDocumentStaticFieldSignature(val *TemplateResponseDocumentStaticFieldSignature) *NullableTemplateResponseDocumentStaticFieldSignature {
	return &NullableTemplateResponseDocumentStaticFieldSignature{value: val, isSet: true}
}

func (v NullableTemplateResponseDocumentStaticFieldSignature) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateResponseDocumentStaticFieldSignature) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


