/*
Dropbox Sign API

Dropbox Sign v3 API

API version: 3.0.0
Contact: apisupport@hellosign.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TemplateResponseDocumentStaticFieldDropdown type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateResponseDocumentStaticFieldDropdown{}

// TemplateResponseDocumentStaticFieldDropdown This class extends `TemplateResponseDocumentStaticFieldBase`
type TemplateResponseDocumentStaticFieldDropdown struct {
	// The type of this static field. See [field types](/api/reference/constants/#field-types).  * Text Field uses `TemplateResponseDocumentStaticFieldText` * Dropdown Field uses `TemplateResponseDocumentStaticFieldDropdown` * Hyperlink Field uses `TemplateResponseDocumentStaticFieldHyperlink` * Checkbox Field uses `TemplateResponseDocumentStaticFieldCheckbox` * Radio Field uses `TemplateResponseDocumentStaticFieldRadio` * Signature Field uses `TemplateResponseDocumentStaticFieldSignature` * Date Signed Field uses `TemplateResponseDocumentStaticFieldDateSigned` * Initials Field uses `TemplateResponseDocumentStaticFieldInitials`
	Type string `json:"type"`
}

// NewTemplateResponseDocumentStaticFieldDropdown instantiates a new TemplateResponseDocumentStaticFieldDropdown object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateResponseDocumentStaticFieldDropdown(type_ string) *TemplateResponseDocumentStaticFieldDropdown {
	this := TemplateResponseDocumentStaticFieldDropdown{}
	this.Type = type_
	var signer string = "me_now"
	this.Signer = &signer
	return &this
}

// NewTemplateResponseDocumentStaticFieldDropdownWithDefaults instantiates a new TemplateResponseDocumentStaticFieldDropdown object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateResponseDocumentStaticFieldDropdownWithDefaults() *TemplateResponseDocumentStaticFieldDropdown {
	this := TemplateResponseDocumentStaticFieldDropdown{}
	var type_ string = "dropdown"
	this.Type = type_
	return &this
}

// GetType returns the Type field value
func (o *TemplateResponseDocumentStaticFieldDropdown) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TemplateResponseDocumentStaticFieldDropdown) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TemplateResponseDocumentStaticFieldDropdown) SetType(v string) {
	o.Type = v
}

func (o TemplateResponseDocumentStaticFieldDropdown) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateResponseDocumentStaticFieldDropdown) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

type NullableTemplateResponseDocumentStaticFieldDropdown struct {
	value *TemplateResponseDocumentStaticFieldDropdown
	isSet bool
}

func (v NullableTemplateResponseDocumentStaticFieldDropdown) Get() *TemplateResponseDocumentStaticFieldDropdown {
	return v.value
}

func (v *NullableTemplateResponseDocumentStaticFieldDropdown) Set(val *TemplateResponseDocumentStaticFieldDropdown) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateResponseDocumentStaticFieldDropdown) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateResponseDocumentStaticFieldDropdown) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateResponseDocumentStaticFieldDropdown(val *TemplateResponseDocumentStaticFieldDropdown) *NullableTemplateResponseDocumentStaticFieldDropdown {
	return &NullableTemplateResponseDocumentStaticFieldDropdown{value: val, isSet: true}
}

func (v NullableTemplateResponseDocumentStaticFieldDropdown) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateResponseDocumentStaticFieldDropdown) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


