/*
Dropbox Sign API

Dropbox Sign v3 API

API version: 3.0.0
Contact: apisupport@hellosign.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TemplateResponseDocumentFormFieldInitials type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateResponseDocumentFormFieldInitials{}

// TemplateResponseDocumentFormFieldInitials This class extends `TemplateResponseDocumentFormFieldBase`
type TemplateResponseDocumentFormFieldInitials struct {
	// The type of this form field. See [field types](/api/reference/constants/#field-types).  * Text Field uses `TemplateResponseDocumentFormFieldText` * Dropdown Field uses `TemplateResponseDocumentFormFieldDropdown` * Hyperlink Field uses `TemplateResponseDocumentFormFieldHyperlink` * Checkbox Field uses `TemplateResponseDocumentFormFieldCheckbox` * Radio Field uses `TemplateResponseDocumentFormFieldRadio` * Signature Field uses `TemplateResponseDocumentFormFieldSignature` * Date Signed Field uses `TemplateResponseDocumentFormFieldDateSigned` * Initials Field uses `TemplateResponseDocumentFormFieldInitials`
	Type string `json:"type"`
}

// NewTemplateResponseDocumentFormFieldInitials instantiates a new TemplateResponseDocumentFormFieldInitials object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateResponseDocumentFormFieldInitials(type_ string) *TemplateResponseDocumentFormFieldInitials {
	this := TemplateResponseDocumentFormFieldInitials{}
	this.Type = type_
	return &this
}

// NewTemplateResponseDocumentFormFieldInitialsWithDefaults instantiates a new TemplateResponseDocumentFormFieldInitials object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateResponseDocumentFormFieldInitialsWithDefaults() *TemplateResponseDocumentFormFieldInitials {
	this := TemplateResponseDocumentFormFieldInitials{}
	var type_ string = "initials"
	this.Type = type_
	return &this
}

// GetType returns the Type field value
func (o *TemplateResponseDocumentFormFieldInitials) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TemplateResponseDocumentFormFieldInitials) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TemplateResponseDocumentFormFieldInitials) SetType(v string) {
	o.Type = v
}

func (o TemplateResponseDocumentFormFieldInitials) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateResponseDocumentFormFieldInitials) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

type NullableTemplateResponseDocumentFormFieldInitials struct {
	value *TemplateResponseDocumentFormFieldInitials
	isSet bool
}

func (v NullableTemplateResponseDocumentFormFieldInitials) Get() *TemplateResponseDocumentFormFieldInitials {
	return v.value
}

func (v *NullableTemplateResponseDocumentFormFieldInitials) Set(val *TemplateResponseDocumentFormFieldInitials) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateResponseDocumentFormFieldInitials) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateResponseDocumentFormFieldInitials) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateResponseDocumentFormFieldInitials(val *TemplateResponseDocumentFormFieldInitials) *NullableTemplateResponseDocumentFormFieldInitials {
	return &NullableTemplateResponseDocumentFormFieldInitials{value: val, isSet: true}
}

func (v NullableTemplateResponseDocumentFormFieldInitials) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateResponseDocumentFormFieldInitials) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


